# Generated by Django 4.2.6 on 2023-10-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Login',
        ),
    ]
